Repository dotnet/docs.pl-pl, pull requests merged in 2018-05, with the labels that each got.

#31 Update index-operator.md in [x] ref
  docs/csharp/language-reference/operators/index-operator.md
Labels: Accepted, Linguistic Suggestion

#35 Update dereference-operator.md in dereference operator ref
  docs/csharp/language-reference/operators/dereference-operator.md
Labels: Accepted, Linguistic Suggestion

#33 Update decrement-operator.md in x-- ref (decrementation operator)
  docs/csharp/language-reference/operators/decrement-operator.md
Labels: In-Progress, Linguistic Suggestion

#32 Update increment-operator.md in x++ ref
  docs/csharp/language-reference/operators/increment-operator.md
Labels: Accepted, Linguistic Suggestion

#42 Update multiplication-assignment-operator.md in x*=y ref
  docs/csharp/language-reference/operators/multiplication-assignment-operator.md
Labels: Accepted, Linguistic Suggestion

#41 Update by.md
  docs/csharp/language-reference/keywords/by.md
Labels: Accepted, Linguistic Suggestion

#39 Update left-shift-assignment-operator.md in x<<=y ref
  docs/csharp/language-reference/operators/left-shift-assignment-operator.md
Labels: Accepted, Linguistic Suggestion

#40 Update right-shift-assignment-operator.md in x>>=y ref
  docs/csharp/language-reference/operators/right-shift-assignment-operator.md
Labels: Accepted, Linguistic Suggestion

#37 Update conditional-and-operator.md in conditional and x && y ref
  docs/csharp/language-reference/operators/conditional-and-operator.md
Labels: Accepted, Linguistic Suggestion

#38 Update assignment-operator.md in x=y operator ref
  docs/csharp/language-reference/operators/assignment-operator.md
Labels: Accepted, Linguistic Suggestion

#48 Update bitwise-complement-operator.md in ~ ref
  docs/csharp/language-reference/operators/bitwise-complement-operator.md
Labels: Accepted, Linguistic Suggestion

#49 Update xor-operator.md in ^ ref
  docs/csharp/language-reference/operators/xor-operator.md
Labels: Accepted, Linguistic Suggestion

#50 Update namespace-alias-qualifer.md in :: alias qualifier
  docs/csharp/language-reference/operators/namespace-alias-qualifer.md
Labels: Accepted, Linguistic Suggestion

#56 Update cs0001.md in CS0001 ref
  docs/csharp/language-reference/compiler-messages/cs0001.md
Labels: Accepted, Linguistic Suggestion

#57 Update cs0006.md in CS0006 ref
  docs/csharp/language-reference/compiler-messages/cs0006.md
Labels: Accepted, Linguistic Suggestion

#58 Update cs0007.md in CS0007 ref
  docs/csharp/language-reference/compiler-messages/cs0007.md
Labels: Accepted, Linguistic Suggestion

#61 Update cs0019.md in CS0019 ref
  docs/csharp/language-reference/compiler-messages/cs0019.md
Labels: In-Progress, Linguistic Suggestion

#65 Update cs0039.md in CS0039 ref
  docs/csharp/language-reference/compiler-messages/cs0039.md
Labels: Accepted, Linguistic Suggestion

#60 Update cs0016.md in CS0016 ref
  docs/csharp/language-reference/compiler-messages/cs0016.md
Labels: Accepted, Linguistic Suggestion

#66 Update cs0050.md in CS0050 ref
  docs/csharp/language-reference/compiler-messages/cs0050.md
Labels: Accepted, Linguistic Suggestion

#71 Update cs0151.md in CS0151 ref
  docs/csharp/language-reference/compiler-messages/cs0151.md
Labels: Accepted, Linguistic Suggestion

#67 Update cs0051.md in CS0051 ref
  docs/csharp/language-reference/compiler-messages/cs0051.md
Labels: Accepted, Linguistic Suggestion

#68 Update cs0052.md in CS0052 ref
  docs/csharp/language-reference/compiler-messages/cs0052.md
Labels: Accepted, Linguistic Suggestion

#70 Update cs0115.md in CS0115 ref
  docs/csharp/language-reference/compiler-messages/cs0115.md
Labels: Accepted, Linguistic Suggestion

#30 Update invocation-operator.md in f(x) ref
  docs/csharp/language-reference/operators/invocation-operator.md
Labels: In-Progress, Linguistic Suggestion, Source Issue

#74 Update cs0229.md in CS0229 ref
  docs/csharp/language-reference/compiler-messages/cs0229.md
Labels: In-Progress, Linguistic Suggestion

#72 Update cs0178.md in CS0178 ref
  docs/csharp/language-reference/compiler-messages/cs0178.md
Labels: Accepted, Linguistic Suggestion

#75 Fix translation of topic to PL
  docs/csharp/language-reference/operators/null-conditional-operators.md
Labels: Accepted, Linguistic Suggestion
