Repository dotnet/docs.pl-pl, pull requests merged in 2018-07, with the labels that each got.

#136 Update cs1921.md in CS1921 ref
  docs/csharp/language-reference/compiler-messages/cs1921.md
Labels: Accepted, Linguistic Suggestion

#135 Update cs1919.md in CS1919 ref
  docs/csharp/language-reference/compiler-messages/cs1919.md
Labels: Accepted, Linguistic Suggestion

#138 Update cs1933.md in CS1933 ref
  docs/csharp/language-reference/compiler-messages/cs1933.md
Labels: Accepted, Linguistic Suggestion

#137 Update cs1926.md in CS1926 ref
  docs/csharp/language-reference/compiler-messages/cs1926.md
Labels: Accepted, Linguistic Suggestion

#146 Update translation [a-e-statements.md]
  docs/visual-basic/language-reference/statements/a-e-statements.md
Labels: Accepted, Linguistic Suggestion

#155 Update translation [f-p-statements.md]
  docs/visual-basic/language-reference/statements/f-p-statements.md
Labels: In-Progress, Linguistic Suggestion

#156 Update translation [q-z-statements.md]
  docs/visual-basic/language-reference/statements/q-z-statements.md
Labels: Accepted, Linguistic Suggestion

#139 Update translation [then-statement.md]
  docs/visual-basic/language-reference/statements/then-statement.md
Labels: Accepted, Linguistic Suggestion

#144 Update translation [clauses.md]
  docs/visual-basic/language-reference/statements/clauses.md
Labels: Accepted, Linguistic Suggestion

#145 Update translation [statements\index.md]
  docs/visual-basic/language-reference/statements/index.md
Labels: Accepted, Linguistic Suggestion

#149 Update cs1941.md in CS1941 ref
  docs/csharp/language-reference/compiler-messages/cs1941.md
Labels: Accepted, Linguistic Suggestion

#150 Update translation [as-clause.md]
  docs/visual-basic/language-reference/statements/as-clause.md
Labels: Accepted, Linguistic Suggestion

#151 Update translation [error-statement.md]
  docs/visual-basic/language-reference/statements/error-statement.md
Labels: Accepted, Linguistic Suggestion

#153 Update cs1942.md in CS1942 ref
  docs/csharp/language-reference/compiler-messages/cs1942.md
Labels: Accepted, Linguistic Suggestion

#152 Update translation [attribute-list.md]
  docs/visual-basic/language-reference/statements/attribute-list.md
Labels: Accepted, Linguistic Suggestion

#141 Update cs1936.md in CS1936 ref
  docs/csharp/language-reference/compiler-messages/cs1936.md
Labels: Accepted, Linguistic Suggestion

#142 Update translation [structure-statement.md]
  docs/visual-basic/language-reference/statements/structure-statement.md
Labels: Accepted, Linguistic Suggestion

#154 Update translation [erase-statement.md]
  docs/visual-basic/language-reference/statements/erase-statement.md
Labels: Accepted, Linguistic Suggestion

#159 Update translation [stop-statement.md]
  docs/visual-basic/language-reference/statements/stop-statement.md
Labels: Accepted, Linguistic Suggestion

#158 Update translation [class-statement.md]
  docs/visual-basic/language-reference/statements/class-statement.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#163 Update cs1946.md in CS1946 ref
  docs/csharp/language-reference/compiler-messages/cs1946.md
Labels: Accepted, Linguistic Suggestion

#160 Update cs1943.md in CS1943 ref
  docs/csharp/language-reference/compiler-messages/cs1943.md
Labels: Accepted, Linguistic Suggestion

#164 Update cs2032.md in CS2032 ref
  docs/csharp/language-reference/compiler-messages/cs2032.md
Labels: Accepted, Linguistic Suggestion

#157 Update [end-keyword-statement.md]
  docs/visual-basic/language-reference/statements/end-keyword-statement.md
Labels: In-Progress, Linguistic Suggestion, Source Issue

#140 Update translation [into-clause.md]
  docs/visual-basic/language-reference/statements/into-clause.md
Labels: Accepted, Linguistic Suggestion
