Repository dotnet/docs.pl-pl, pull requests merged in 2018-06, with the labels that each got.

#76 Update cs0233.md in CS0233 ref
  docs/csharp/language-reference/compiler-messages/cs0233.md
Labels: Accepted, Linguistic Suggestion

#77 Update cs0260.md in CS0260 ref
  docs/csharp/language-reference/compiler-messages/cs0260.md
Labels: Accepted, Linguistic Suggestion

#79 Update cs0266.md in CS0266 ref
  docs/csharp/language-reference/compiler-messages/cs0266.md
Labels: Accepted, Linguistic Suggestion

#84 Update cs0445.md in CS0445 ref
  docs/csharp/language-reference/compiler-messages/cs0445.md
Labels: In-Progress, Linguistic Suggestion

#83 Update cs0417.md in CS0417 ref
  docs/csharp/language-reference/compiler-messages/cs0417.md
Labels: In-Progress, Linguistic Suggestion

#78 Update index.md in csharp/programming-guide
  docs/csharp/programming-guide/index.md
Labels: Accepted, Linguistic Suggestion

#85 Update cs0446.md in CS0446 ref
  docs/csharp/language-reference/compiler-messages/cs0446.md
Labels: Accepted, Linguistic Suggestion

#86 Update cs0504.md in CS0504 ref
  docs/csharp/language-reference/compiler-messages/cs0504.md
Labels: Accepted, Linguistic Suggestion

#81 Update cs0310.md in CS0310 ref
  docs/csharp/language-reference/compiler-messages/cs0310.md
Labels: Accepted, Linguistic Suggestion

#82 Update docs/csharp/getting-started/index.md
  docs/csharp/getting-started/index.md
Labels: Accepted, Linguistic Suggestion

#87 Update cs0523.md in CS0523 ref
  docs/csharp/language-reference/compiler-messages/cs0523.md
Labels: Accepted, Linguistic Suggestion

#89 Update cs0563.md in CS0563 ref
  docs/csharp/language-reference/compiler-messages/cs0563.md
Labels: Accepted, Linguistic Suggestion

#88 Update cs0552.md in CS0552 ref
  docs/csharp/language-reference/compiler-messages/cs0552.md
Labels: Accepted, Linguistic Suggestion

#90 Update cs0570.md in CS0570 ref
  docs/csharp/language-reference/compiler-messages/cs0570.md
Labels: Accepted, In-Progress, Linguistic Suggestion

#91 Update cs0571.md in CS0571 ref
  docs/csharp/language-reference/compiler-messages/cs0571.md
Labels: Accepted, Linguistic Suggestion

#92 Update cs0579.md in CS0579 ref
  docs/csharp/language-reference/compiler-messages/cs0579.md
Labels: Accepted, Linguistic Suggestion

#94 Update cs0702.md in CS0702 ref
  docs/csharp/language-reference/compiler-messages/cs0702.md
Labels: Accepted, Linguistic Suggestion

#93 Update cs0616.md in CS0616 ref
  docs/csharp/language-reference/compiler-messages/cs0616.md
Labels: Accepted, Linguistic Suggestion

#96 Update cs0826.md in CS0826 ref
  docs/csharp/language-reference/compiler-messages/cs0826.md
Labels: Accepted, Linguistic Suggestion

#97 Update cs0834.md in CS0834 ref
  docs/csharp/language-reference/compiler-messages/cs0834.md
Labels: Accepted, Linguistic Suggestion

#98 Update cs0840.md in CS0840 ref
  docs/csharp/language-reference/compiler-messages/cs0840.md
Labels: Accepted, Linguistic Suggestion

#100 Update cs0845.md in CS0845 ref
  docs/csharp/language-reference/compiler-messages/cs0845.md
Labels: Accepted, Linguistic Suggestion

#102 Update cs1009.md in CS1009 ref
  docs/csharp/language-reference/compiler-messages/cs1009.md
Labels: Accepted, Linguistic Suggestion

#107 Update cs1061.md in CS1061 ref
  docs/csharp/language-reference/compiler-messages/cs1061.md
Labels: Accepted, Linguistic Suggestion

#106 Update cs1029.md in CS1029 ref
  docs/csharp/language-reference/compiler-messages/cs1029.md
Labels: Accepted, Linguistic Suggestion

#105 Update cs1026.md in CS1026 ref
  docs/csharp/language-reference/compiler-messages/cs1026.md
Labels: Accepted, Linguistic Suggestion

#104 Update cs1019.md in CS1019 ref
  docs/csharp/language-reference/compiler-messages/cs1019.md
Labels: Accepted, Linguistic Suggestion

#108 Update cs1501.md in CS1501 ref
  docs/csharp/language-reference/compiler-messages/cs1501.md
Labels: Accepted, Linguistic Suggestion

#109 Update cs1567.md in CS1567 ref
  docs/csharp/language-reference/compiler-messages/cs1567.md
Labels: Accepted, Linguistic Suggestion

#120 Update cs1704.md in CS1704 ref
  docs/csharp/language-reference/compiler-messages/cs1704.md
Labels: Accepted, Linguistic Suggestion

#110 Update cs1640.md in CS1640 ref
  docs/csharp/language-reference/compiler-messages/cs1640.md
Labels: Accepted, Linguistic Suggestion

#117 Translation
  docs/standard/exceptions/how-to-create-user-defined-exceptions.md
Labels: Accepted, Linguistic Suggestion

#119 Update cs1674.md in CS1674 ref
  docs/csharp/language-reference/compiler-messages/cs1674.md
Labels: Accepted, Linguistic Suggestion

#118 Update cs1644.md in CS1644 ref
  docs/csharp/language-reference/compiler-messages/cs1644.md
Labels: Accepted, Linguistic Suggestion

#123 Update cs1708.md in CS1708 ref
  docs/csharp/language-reference/compiler-messages/cs1708.md
Labels: Accepted, Linguistic Suggestion

#128 Update cs1716.md in CS1716 ref
  docs/csharp/language-reference/compiler-messages/cs1716.md
Labels: Accepted, Linguistic Suggestion

#131 Update cs1726.md in CS1726 ref
  docs/csharp/language-reference/compiler-messages/cs1726.md
Labels: Accepted, Linguistic Suggestion

#133 Update cs1729.md in CS1729 ref
  docs/csharp/language-reference/compiler-messages/cs1729.md
Labels: Accepted, Linguistic Suggestion

#130 Update cs1721.md in CS1721 ref
  docs/csharp/language-reference/compiler-messages/cs1721.md
Labels: Accepted, Linguistic Suggestion
